name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.message, '[build-image]')

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/getdirectholidays/gdh-web:latest .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - name: Push Docker Image
        run: docker push ghcr.io/getdirectholidays/gdh-web:latest
